### ISSUE TITLE
Unreliable Organization Avatar Rendering

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#1]
There's a bug where the organization avatar images do not reliably display on each tile. The code is a bit messy around the state management of this so I expect this to be a pretty tricky problem to solve.

For me, when I first open up the UI, when the tasks are loaded from the cache they never render the images. However when I login with GitHub, they do render:

![work ubq fi_](https://github.com/ubiquity/devpool-directory-ui/assets/4975670/fc0a4220-edab-4179-869f-cac64d5c3b64)

I remember the original obstacle was related to rate limits (when not logged in, can only make something like 60 requests in a minute; this is problematic when there are 30+ issues (issue contents, and organization avatar is already two requests.) 

I tried implementing a cache system for issues (done, and well implemented) as well as the avatars (not well implemented.)

**Comment by 0x4007** [comment]
Weird that there are two separate credits for review comments.

**Comment by wannacfuture** [comment]
We need to take a look at review comment incentive part. Let me try
