### ISSUE TITLE
Optimize Avatar Requests

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#105]
> ![image](https://github.com/user-attachments/assets/574041c7-9c7e-46e3-8d97-7ebb30726958)
> 
> 
> Getting this will have to handle in a new task
> 

_Originally posted by @0x4007 in https://github.com/ubiquity/work.ubq.fi/issues/104#issuecomment-2392454878_

**Comment by zugdev** [comment]
We just need to avoid redundant calls, only one execution per organization should be able to fetch the image and store it in cache, as all `fetchAvatar` run at the same time the code fails to safe guard that and multiple requests are being made.

My solution is, as stated above, to only let one execution per organization to fetch from either the DB or from network and store it in cache. 

![image](https://github.com/user-attachments/assets/7b02222f-98b4-47a1-bc6e-1ff73cc4312b)

Notice in console that multiple "threads" keep waiting while a single one goes in fetches and caches the image for the other requests.

**Comment by 0x4007** [comment]
@zugdev I still need some time to set up UUSD payouts apologies.

**Comment by 0x4007** [comment]
> <details><summary><b><h3>&nbsp;<a href="https://pay.ubq.fi?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweEM2ZWQ0ZjUyMGY2QTRlNERDMjcyNzM1MDkyMzliN0Y4QTY4ZDIwNjgiLCJhbW91bnQiOiI4NDI4NDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjI5MzI0ODQzNjM4MDU2NzQyOTA5Nzk2MTAwMzY1Nzk2OTc4MjQ5MTkxMTkwMjA4Nzg5NTExMjM5MzAyMTY3NDQ1Nzg1Njg3OTkwNjU1IiwiZGVhZGxpbmUiOiI1Nzg5NjA0NDYxODY1ODA5NzcxMTc4NTQ5MjUwNDM0Mzk1MzkyNjYzNDk5MjMzMjgyMDI4MjAxOTcyODc5MjAwMzk1NjU2NDgxOTk2NyJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweGJCNjg5ZkRBYkJmYzBhZTkxMDI4NjNFMDExRDNmODk3YjA3OWM4MEYiLCJyZXF1ZXN0ZWRBbW91bnQiOiI4NDI4NDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4OTA1MWVEYTk2ZEI0MTljOTY3MTg5RjRBYzMwM2EyOTBGMzMyNzY4MCIsInNpZ25hdHVyZSI6IjB4MTA2NzUwZmVmMzdmOWNjZTBiN2M3NDc0YjI4ZDA2YTk4Yjk2MTU2NDdmOGVhNTQyODExZDMxZjkyM2ExNGI2NzAyOWQyNWI0M2Y4MWU3MTg5ZDZhZTUwNmUyZmZkOTkwYzI1ZDU3MTI1MTY5YTQ3OWNiNWE1YzIxNjBjOGIwNjgxYyIsIm5ldHdvcmtJZCI6MTAwfV0=" target="_blank" rel="noopener">[ 84.284 UUSD ]</a>&nbsp;</h3><h6>@zugdev</h6></b></summary><h6>Contributions Overview</h6><table><thead><tr><th>View</th><th>Contribution</th><th>Count</th><th>Reward</th></tr></thead><tbody><tr><td>Issue</td><td>Task</td><td>1</td><td>75</td></tr><tr><td>Issue</td><td>Comment</td><td>1</td><td>9.284</td></tr><tr><td>Review</td><td>Comment</td><td>2</td><td>0</td></tr></tbody></table><h6>Conversation Incentives</h6><table><thead><tr><th>Comment</th><th>Formatting</th><th>Relevance</th><th>Reward</th></tr></thead><tbody><tr><td><h6><a href="https://github.com/ubiquity/work.ubq.fi/issues/105#issuecomment-2395670401" target="_blank" rel="noopener">We just need to avoid redundant calls, only one execution per or&hellip;</a></h6></td><td><details><summary>5</summary><pre>content:&#13;  content:&#13;    p:&#13;      score: 0&#13;      elementCount: 4&#13;    img:&#13;      score: 5&#13;      elementCount: 1&#13;  result: 5&#13;regex:&#13;  wordCount: 94&#13;  wordValue: 0.1&#13;  result: 4.76&#13;</pre></details></td><td>0.9</td><td>9.284</td></tr><tr><td><h6><a href="https://github.com/ubiquity/work.ubq.fi/pull/106" target="_blank" rel="noopener">Resolves #105This allows only a single request for avatar per &hellip;</a></h6></td><td><details><summary>0</summary><pre>content:&#13;  content:&#13;    p:&#13;      score: 0&#13;      elementCount: 3&#13;  result: 0&#13;regex:&#13;  wordCount: 91&#13;  wordValue: 0&#13;  result: 0&#13;</pre></details></td><td>0.9</td><td>-</td></tr><tr><td><h6><a href="https://github.com/ubiquity/work.ubq.fi/pull/106#issuecomment-2395687294" target="_blank" rel="noopener">@0x4007 I've let the &#96;console.log&#96; statements in the cod&hellip;</a></h6></td><td><details><summary>7.5</summary><pre>content:&#13;  content:&#13;    p:&#13;      score: 0&#13;      elementCount: 7&#13;    ol:&#13;      score: 1&#13;      elementCount: 1&#13;    li:&#13;      score: 0.5&#13;      elementCount: 3&#13;    img:&#13;      score: 5&#13;      elementCount: 1&#13;  result: 7.5&#13;regex:&#13;  wordCount: 114&#13;  wordValue: 0.2&#13;  result: 11.2&#13;</pre></details></td><td>0.8</td><td>-</td></tr></tbody></table></details><details><summary><b><h3>&nbsp;<a href="undefined" target="_blank" rel="noopener">[ 3.18 UUSD ]</a>&nbsp;</h3><h6>@0x4007</h6></b></summary><h6>Contributions Overview</h6><table><thead><tr><th>View</th><th>Contribution</th><th>Count</th><th>Reward</th></tr></thead><tbody><tr><td>Issue</td><td>Specification</td><td>1</td><td>3.18</td></tr></tbody></table><h6>Conversation Incentives</h6><table><thead><tr><th>Comment</th><th>Formatting</th><th>Relevance</th><th>Reward</th></tr></thead><tbody><tr><td><h6><a href="https://github.com/ubiquity/work.ubq.fi/issues/105" target="_blank" rel="noopener">_Originally posted by @0x4007 in https://github.com/ubiquity/wor&hellip;</a></h6></td><td><details><summary>0</summary><pre>content:&#13;  content:&#13;    p:&#13;      score: 0&#13;      elementCount: 1&#13;    em:&#13;      score: 0&#13;      elementCount: 1&#13;  result: 0&#13;regex:&#13;  wordCount: 16&#13;  wordValue: 0.1&#13;  result: 1.06&#13;</pre></details></td><td>1</td><td>3.18</td></tr></tbody></table></details>
> 

My URL is broken again @gentlementlegen this shouldn't render unless it's valid

**Comment by 0x4007** [comment]
Also no image credit. It's broken too

**Comment by zugdev** [comment]
Yo @0x4007 there are more code optimizations I could implement. For example, `applyAvatarsToIssues` is called 4x, when a single one is enough. Perhaps a optimize caching issue?

**Comment by 0x4007** [comment]
Sure file an issue

**Comment by zugdev** [comment]
> @zugdev I still need some time to set up UUSD payouts apologies.

No worries bro

**Comment by gentlementlegen** [comment]
@0x4007 It is still giving
```
Error: Failed to get token decimals for token: 0xC6ed4f520f6A4e4DC27273509239b7F8A68d2068
```

Is there anything special going on with this address?

**Comment by zugdev** [comment]
> 0xC6ed4f520f6A4e4DC27273509239b7F8A68d2068

You could be reading from wrong chain, but it's UUSD in Gnosis and has 18 decimals: https://gnosisscan.io/address/0xC6ed4f520f6A4e4DC27273509239b7F8A68d2068#readProxyContract
