### ISSUE TITLE
Remove Redundant Calls and Optimize Caching

### ISSUE THREAD

**Issue by zugdev** [ubiquity/work.ubq.fi#108]
While working through some issues I noticed there are some caching optimizations pending, redundant calls being made and load time could improve. A clear example was that for each issue the organization's avatar was fetched, meaning that for 144 issues within 3 repos, where 3 calls could have been made we were making 144. This was solved at #106. 

Some code parts are also not respecting single responsibility principle, there are tries to set cache outside of a fetch function. This leads to resource waste and subsequently worse performance. 

For example, the following O(n) function where n is issues array length is being called 4 different times in different places:

```
export function applyAvatarsToIssues() {
  const container = taskManager.getContainer();
  const issueElements = Array.from(container.querySelectorAll(".issue-element-inner"));

  issueElements.forEach((issueElement) => {
    const orgName = issueElement.querySelector(".organization-name")?.textContent;
    if (orgName) {
      const avatarUrl = organizationImageCache.get(orgName);
      if (avatarUrl) {
        const avatarImg = issueElement.querySelector("img");
        if (avatarImg) {
          avatarImg.src = URL.createObjectURL(avatarUrl);
        }
      }
    }
  });
}
```

![image](https://github.com/user-attachments/assets/a0551a06-f3f4-4fb3-b8b0-4070b1b5e294)

The code base could benefit from general optimizations and a principle-based approach. I believe a 2-3 hour thorough review should be enough to identify, test and fix some of the problems.

**Comment by zugdev** [comment]
@0x4007 As you can see in the following snippet, we spend a couple lines checking cache validity. Two of those checks, lines 30-38, validate whether a user logged-in state has changed,  and if it has then cache should be reset. 

https://github.com/ubiquity/work.ubq.fi/blob/c70bfc5254373aaa91b7ee7dd9a15b86cd7e77dd/src/home/fetch-github/fetch-and-display-previews.ts#L26-L57

Currently it seems there is no extra feature for authenticated users, is this a long term plan to show different issues as in a *My Contributions* / *My Tasks*, or even some control features for org members? I see that it was introduced in [this PR](https://github.com/ubiquity/work.ubq.fi/pull/24) and all code to see "private repos" has apparently been removed. Should this be kept or removed?

I will redesign cache integrity handling and would be very happy to know about this.

**Comment by 0x4007** [comment]
Yes we need GitHub login for two reasons currently:

1. Private issues. The idea is that partners can add their private repos to our directory. If you want to be able to read them, you need access via your GitHub account. Basically we have another private version of the DevPool directory backend but that's still not really well implemented. 
2. Referral tracking. When you login, we save a referral code for future referral rewards. It's pretty much the only place in our system we can do this.

**Comment by 0x4007** [comment]
Halfway done setting up UUSD. Gas fees spiked high when I tried yesterday unfortunately.

**Comment by zugdev** [comment]
> Halfway done setting up UUSD. Gas fees spiked high when I tried yesterday unfortunately. 

Let me know if I can assist you somehow!
