### ISSUE TITLE
Remove unused code, rename legacy functions and document to improve DX

### ISSUE THREAD

**Issue by zugdev** [ubiquity/work.ubq.fi#113]
**Once #108 is complete**

There are some remaining types and files which have lost purpose and meaning. For example, `fetch-issues-preview.ts` doesn't even have to do with issues or previews now:

https://github.com/ubiquity/work.ubq.fi/blob/c70bfc5254373aaa91b7ee7dd9a15b86cd7e77dd/src/home/fetch-github/fetch-issues-preview.ts#L1-L5

There are other remaining senseless pieces which can be safely deleted. 

I also believe in renaming actively used functions whose names are inappropriate. The "FromNetwork" chunk of this function's name doesn't mean anything since the approach to fetching issues changed to JSON.

https://github.com/ubiquity/work.ubq.fi/blob/c70bfc5254373aaa91b7ee7dd9a15b86cd7e77dd/src/home/fetch-github/fetch-and-display-previews.ts#L59

An hour of well thought renaming, deletions and comments would do good to this codebase.
###### Similar [^01^]

[^01^]: [Remove Redundant Calls and Optimize Caching](https://www.github.com/ubiquity/work.ubq.fi/issues/108) 80%

**Comment by 0x4007** [comment]
This scope of work should be handled in that previous task
