### ISSUE TITLE
Deep Links

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#118]
- We should push and pop browser history when opening issues. 
- We need to account for proposals and for tasks. 
- We need to automatically open the task/proposal when the page is loaded with the url representing it. Maybe a # in the URL with the issue ID will be sufficient.

**Comment by 0x4007** [comment]
@gentlementlegen rfc on start

**Comment by gentlementlegen** [comment]
Mentioned quite a few times: https://github.com/ubiquity-os/ubiquity-os-kernel/issues/120
