### ISSUE TITLE
Keyboard Navigation Broken

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#12]
I just realized now that the keyboard navigation is not loading the new previews. Before you could use the up and down arrow keys to surf through the issues quickly.

**Comment by gentlementlegen** [comment]
@pavlovcik Might need a little more details for this one:
- technically the arrow navigation works fine, but I guess you meant the preview opening on the right side showing a preview of the issue does not update while issues are navigated through the keyboard keys?
- is there a dev supabase, or should it be set locally instead? I linked with the same one as the website, problem being that it logs you in but on the https://work.ubq.fi/ website, not locally

**Comment by 0x4007** [comment]
The Supabase is only used for GitHub user registration. It's just connecting to the same one the bot has access to for now. It should be the same as the other one you might have used in this case. 

The current database we are using system wide still needs refactoring regarding its schema. I would consider it somewhat temporary at least until we migrate the bot to its kernel-plugin architecture and get it stable again.

**Comment by 0x4007** [comment]
I think the comment incentive quantitative calculation isn't working as expected. It's displaying a high word count but not crediting for it. Perhaps the `li` tag is being ignored for some reason. 

But really happy to see that claims work again. 

@ubiquity/software-development @ubiquity/business-development perhaps you all can revisit your old permits to see if they are claimable now that @barebind fixed the UI? (thanks for that!)

My claim: 

https://gnosisscan.io/tx/0x67d2cdc3d6cc7d95f140decf6fbaea63c69211d6e5b26271b4693ab4f487622d
