### ISSUE TITLE
keyboard navigation buttons over commit id in certain page widths 

### ISSUE THREAD

**Issue by zugdev** [ubiquity/work.ubq.fi#127]
As you can see in the screenshot (at the bottom-right corner), for some tablet-like widths, the navigation buttons are overlapping with the commit id. On mobile view the commit id is hidden, so just making sure the size triggers are the same to show the buttons and hide the commit id should fix it.

![image](https://github.com/user-attachments/assets/83376fb6-99ea-47c0-8b4e-6554cf0050b4)

**Comment by 0x4007** [comment]
Perhaps we can reverse the side the commit ID and faq is on. 

( ? )   1234abcd

**Comment by zugdev** [comment]
Doesn't look right.

![image](https://github.com/user-attachments/assets/cc1b18e8-2d7e-47bd-af6a-58f7c8a95f2b)

**Comment by zugdev** [comment]
Give me a personal limit of 99 tasks :1st_place_medal:

**Comment by gentlementlegen** [comment]
The task limit has to be fixed, should not count if you have pull-requests opened against issues: https://github.com/ubiquity-os-marketplace/command-start-stop/issues/28

**Comment by zugdev** [comment]
> The task limit has to be fixed, should not count if you have pull-requests opened against issues: https://github.com/ubiquity-os-marketplace/command-start-stop/issues/28

Was just joking, sorry

**Comment by gentlementlegen** [comment]
@zugdev No no I got it just saying that it actually is a real issue haha, you should be able to start tasks technically, this is not properly implemented.
