### ISSUE TITLE
Allow a third click to disable sorting

### ISSUE THREAD

**Issue by zugdev** [ubiquity/work.ubq.fi#132]
Right now, once you click to sort issues by some criteria there is no way to unsort them. Usually apps have a three clicks cycle where first click sorts top to bottom, second: bottom to top and a third disables the sorting. Not having this is not harmful but it's a worthy detail. Also we could eventually implement a standard sorting (priority based or paid placement by our partners) and we would want to let the user see it more than once.

https://github.com/user-attachments/assets/bda2629d-41c2-418e-a909-1cdb734409dc

**Comment by Atharva-Kanherkar** [comment]
@zugdev The idea would be adding an "Asc" "Desc" And "None" options so that user can select from all of these. Am i right on this?

**Comment by zugdev** [comment]
Yes, we currently only have the equivalent to ascending and descending.

**Comment by Atharva-Kanherkar** [comment]
@zugdev We have an arrow right now on which we click and it changes it to reverse order. Adding a "none" button would basically distort the UI. Can we do something like this :
 First Click: Sets sorting to "normal" (asc).
Second Click: Reverses sorting (desc, reverse).
Third Click: Disables sorting ("none"), which means issues will be shown in the original order or no active sorting.

**Comment by zugdev** [comment]
> Third Click: Disables sorting ("none"), which means issues will be shown in the original order or no active sorting.

Yes that's the idea, "none" should be the initial non-sorting state.

**Comment by Atharva-Kanherkar** [comment]
> > Third Click: Disables sorting ("none"), which means issues will be shown in the original order or no active sorting.
> 
> Yes that's the idea, "none" should be the initial non-sorting state.

Sure! Ill start working on this.

**Comment by Atharva-Kanherkar** [comment]
hi @zugdev kindly review the PR!
