### ISSUE TITLE
White Labeling Header

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#141]
Extending #128

We can replace the header logo with the GitHub organization avatar and then use the organization name. 

For example

(AAVE logo) AAVE DIRECTORY

Will need to be cautious to handle long organization names like UbiquityOS Marketplace for short width screens!

**Comment by The-Gamer-01** [comment]
Do you mean like this?(this is only a easy demo)
![image](https://github.com/user-attachments/assets/365955d1-bc54-4e2d-97cc-62b8347d5b91)

**Comment by 0x4007** [comment]
No the header is where it says devpool directory

**Comment by zugdev** [comment]
I will do this one too, pls assign I am still glitched

**Comment by 0x4007** [comment]
> I will do this one too, pls assign I am still glitched

Consider fixing the glitch!

**Comment by zugdev** [comment]
is rewards bot dead? @gentlementlegen

**Comment by gentlementlegen** [comment]
@zugdev The `fetch` failed to reach the network so the plugin never started.
