### ISSUE TITLE
fix ugly scrollbars that appear on previews

### ISSUE THREAD

**Issue by zugdev** [ubiquity/work.ubq.fi#146]
I thought this was a thing with my browser (Opera GX) but I tried out a few and it still looks weird. I remember sometimes it didn't look like this, specially when testing responsiveness.

Opera GX:
![image](https://github.com/user-attachments/assets/f4dc6653-1cf1-42f9-a6b4-aa131492ba7a)

Edge:
![image](https://github.com/user-attachments/assets/9724e96d-3aa5-4e5f-9305-c85b995a2544)

Chrome:
![image](https://github.com/user-attachments/assets/248041c9-103a-441b-9c7c-65eafe440aaf)

Firefox:
![image](https://github.com/user-attachments/assets/c9d6c104-b723-49d9-8bd7-a65c25363c8f)

Brave:
![image](https://github.com/user-attachments/assets/f3e84419-2445-4100-9df9-ec4177154f4a)

I am guessing Firefox and Safari work by what's in use:
```
&::-webkit-scrollbar {
    display: none;
  }
```

There might be a way to make this work.

**Comment by zugdev** [comment]
@0x4007 though I had the hassle of downloading all browsers and testing, I think my reward is at least a little buffed. perhaps the exponential decrease in word value could be applied to links and images, even if it's a little less steep

**Comment by 0x4007** [comment]
We will limit rewards to assignee amount max, some day.
