### ISSUE TITLE
add an UI element to indicate taken/free issues

### ISSUE THREAD

**Issue by zugdev** [ubiquity/work.ubq.fi#148]
A big advantage of scouting issues on GitHub instead of the directory is that we can't differentiate between taken and open issues. GitHub solves that by displaying the assignee's PFP:

![image](https://github.com/user-attachments/assets/7f60f3d3-5a8b-45fd-9ae6-aac4d8c2cac1)

We should add a UI element to differentiate between issues with an assignee and issues without one, also allowing to filter by the presence or absence of assignee. This should be very easy to do given that the issue object has the following structure:

```json
{
       "assignee": {
        "login": "imabutahersiddik",
        "id": 138387257,
        "node_id": "U_kgDOCD-fOQ",
        "avatar_url": "https://avatars.githubusercontent.com/u/138387257?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/imabutahersiddik",
        "html_url": "https://github.com/imabutahersiddik",
        "followers_url": "https://api.github.com/users/imabutahersiddik/followers",
        "following_url": "https://api.github.com/users/imabutahersiddik/following{/other_user}",
        "gists_url": "https://api.github.com/users/imabutahersiddik/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/imabutahersiddik/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/imabutahersiddik/subscriptions",
        "organizations_url": "https://api.github.com/users/imabutahersiddik/orgs",
        "repos_url": "https://api.github.com/users/imabutahersiddik/repos",
        "events_url": "https://api.github.com/users/imabutahersiddik/events{/privacy}",
        "received_events_url": "https://api.github.com/users/imabutahersiddik/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": false
    },
    "url": "https://api.github.com/repos/ubiquity-os-marketplace/text-conversation-rewards/issues/152",
    "repository_url": "https://api.github.com/repos/ubiquity-os-marketplace/text-conversation-rewards",
    "title": "Failed to save permit",
   ...
}
```

An instance as example:

![image](https://github.com/user-attachments/assets/5cc2baf6-fb59-4f1c-af47-842c1321e928)

**Comment by 0x4007** [comment]
The task is not supposed to be visible if it's taken. Perhaps this feature is broken now? Maybe this approach does make sense for the ability to see every task in the network, but then to be able to further sort for availability. 

These days I even use the UI to quickly find some issue I was thinking about (it's way faster than any official GitHub UI for this purpose) so it could be nice to see regardless of its assigned status.

**Comment by zugdev** [comment]
It's broken, but yes, I imagine the DevPool as an important tooling not only for contributors finding an issue to tackle, but also for code owners to manage/view it all. Therefore I believe this is a nice feature to have. We should find the old broken code and remove it too.

**Comment by 0x4007** [comment]
It's related to the `unavailable` label on the backend. When assigned it would add that label. I suppose the UI would then filter out those with the `unavailable` label.

**Comment by Keyrxng** [comment]
why isnt this done yet lmao?

Is it being priced or is it a core team task?

**Comment by 0x4007** [comment]
I think the specification needs to be redone. It seems that there are two popular use cases of this UI:

1. Finding new available tasks to work on
2. Finding any in progress tasks

I think that by default we should show only the available tasks and we should have a toggle, like a filter button, that shows all of the tasks

**Comment by Keyrxng** [comment]
Relates to https://github.com/ubiquity/work.ubq.fi/issues/168

UI is pretty unusable for newcomers. Whoever has this repo as their scope should surely be making the UI usable as a matter of urgency no?
