### ISSUE TITLE
expand code blocks in preview

### ISSUE THREAD

**Issue by zugdev** [ubiquity/work.ubq.fi#155]
Code blocks in issue previews are currently barely readable, take the image from [this preview](https://devpool.directory/?issue=2208105478) as an example:

![image](https://github.com/user-attachments/assets/d6607fcc-45bc-4854-be26-6244bd4ff51a)

On GitHub it looks like this:

![image](https://github.com/user-attachments/assets/a74c9610-ab7a-4f23-81f6-a7b223cd593d)

Which is much more readable.

**Comment by 0x4007** [comment]
It's tricky to do correctly with css but yeah would be nice

**Comment by zugdev** [comment]
@gentlementlegen apparently permit generation did not run.

**Comment by zugdev** [comment]
This is how it looks now:

![image](https://github.com/user-attachments/assets/04f17544-661b-469e-a43d-933197c740cb)

We could possibly look into a coloring lib in the future.

**Comment by gentlementlegen** [comment]
@zugdev got a lot of fetch request that went loose:
<img width="996" alt="image" src="https://github.com/user-attachments/assets/5ecd8754-2c3b-4e70-af86-80f995bd9e8f">

I will try to regenerate.

**Comment by gentlementlegen** [comment]
It seems we get a lot of errors during runs
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/c7c68c03-9bd7-4cfc-bbfa-fecafebd6ae9">

I am not sure if that's because we start to have too many plugins to call. @0x4007 rfc

**Comment by zugdev** [comment]
My reward seems incorrect. @0x4007 if necessary revoke it.

**Comment by gentlementlegen** [comment]
@zugdev as long as you don't claim it we can regenerate it. Seems that there is a high boost on the specification.

So technically your reward is correct, but I remember somewhere we talked about capping it so it doesn't go higher than the reward of the issue itself or something like that (there currently is a x3 boost on the specs so you got `16.75 * 3 = 50.25`).

**Comment by zugdev** [comment]
> It seems we get a lot of errors during runs
> <img width="1068" alt="image" src="https://github.com/user-attachments/assets/c7c68c03-9bd7-4cfc-bbfa-fecafebd6ae9">
> 
> I am not sure if that's because we start to have too many plugins to call.

I am not an expert in workers but, from my experience with distributed systems, it seems super weird that there isn't a way to wait for resources or schedule a never reverting call. There must be a way to make it deterministic.

**Comment by zugdev** [comment]
> So technically your reward is correct, 

I understand that, initially I thought it was that recent misconfiguration, but that was related to PR author getting review comments credited. I won't claim for now, I will let him decide what should be done in this case.

**Comment by gentlementlegen** [comment]
> > It seems we get a lot of errors during runs
> > <img width="1068" alt="image" src="https://github.com/user-attachments/assets/c7c68c03-9bd7-4cfc-bbfa-fecafebd6ae9">
> > 
> > I am not sure if that's because we start to have too many plugins to call.
> 
> I am not an expert in workers but, from my experience with distributed systems, it seems super weird that there isn't a way to wait for resources or schedule a never reverting call. There must be a way to make it deterministic.
> 

We also have to check the code itself the error might be totally different but logs are not very verbose within Cloud flare. Let's see if it also occurs on the development bot version because it could also mean some problem in the main branch only.

**Comment by zugdev** [comment]
> We also have to check the code itself the error might be totally different but logs are not very verbose within Cloud flare. Let's see if it also occurs on the development bot version because it could also mean some problem in the main branch only. 

I will look into it today.
