### ISSUE TITLE
properly style tables in preview

### ISSUE THREAD

**Issue by zugdev** [ubiquity/work.ubq.fi#159]
A table in an issue description gets correctly converted into an HTML table element, however the style is not as neat as GitHub's. Take [this issue](https://37843ffb.devpool-directory-ui.pages.dev/?issue=2489452377) as an example:

Ours:
![image](https://github.com/user-attachments/assets/75311b29-efae-4d21-9621-2353059a950d)

GitHub's:
![image](https://github.com/user-attachments/assets/9c9d8c92-a94a-4b6d-a4be-9a59574ff7f3)

We should improve this, I believe it's doable with CSS only.

**Comment by zugdev** [comment]
This is cool, but as this PR will be very low effort review, I will allow external contributor to proceed.

**Comment by 0x4007** [comment]
This is a good example of where we should limit the author rewards @gentlementlegen

**Comment by gentlementlegen** [comment]
All the pull requests are awaiting your review I think. There is one for the reward limitation.
