### ISSUE TITLE
fix live reload

### ISSUE THREAD

**Issue by zugdev** [ubiquity/work.ubq.fi#164]
We've recently changed this repo's `package.json` start command to use wrangler pages because of the referral tracker kv implementation. 

```json
"start": "wrangler pages dev --port 8080"
```

This killed the live reload feature, and https://github.com/cloudflare/workers-sdk/issues/4824 we have to pass in a directory after wrangler pages dev to hear changes from. However, passing in `./` wont work since it only reads inside the received directory (non-recursive).

**Comment by zugdev** [comment]
Wrangler only looks specifically inside the directory given, so even though HTML changes are captured, typescript ones aren't. Therefore it is extremely unreliable to get global `ts` changes for example. So I've deprecated the server in favor of wrangler and wrote an observer using esbuild API that watches and rebuilds based on file change.

**Comment by 0x4007** [comment]
> ```diff
> - Relevance / Comment length mismatch!
> ```

@gentlementlegen first time I've seen this in a long time. Production should be stable.

**Comment by gentlementlegen** [comment]
@0x4007 Since the prompt was changed within the last 7 days it is possible that something went wrong, I'll investigate.
