### ISSUE TITLE
proper display for citations

### ISSUE THREAD

**Issue by zugdev** [ubiquity/work.ubq.fi#167]
As can be seen in [this issue](https://work.ubq.fi/?issue=2607517148), citations aren't properly handled and look ugly. There is no viable CSS only solution, but perhaps markdown can fix it.

See the bottom of the picture:

![image](https://github.com/user-attachments/assets/1628adb9-3599-4074-a743-ed46cc82f050)

**Comment by Sadaf-A** [comment]
@zugdev Hey, could you please tell exactly which part is looking ugly and how we should go on about fixing it?

**Comment by zugdev** [comment]
@gentlementlegen think bot is down

**Comment by gentlementlegen** [comment]
@zugdev this repo uses a very outdated configuration which is why it is not working, lemme fix and generate.

**Comment by gentlementlegen** [comment]
Sorry about the spam. Configuration needs lots of changes and it seems that `ncc` didn't compile properly either. Runs for reference: https://github.com/ubiquity-os-marketplace/text-conversation-rewards/actions/runs/12443282930/job/34742289914

**Comment by gentlementlegen** [comment]
@zugdev it seems that conversation rewards on the main branch breaks because of some package upgrade but the bots seems ok, let me investigate and fix.
