### ISSUE TITLE
add a repo searching scorer 

### ISSUE THREAD

**Issue by zugdev** [ubiquity/work.ubq.fi#169]
When searching for a repo, the expected behavior is to see all issues within it. Currently we don't support that:

![image](https://github.com/user-attachments/assets/610689a4-1631-4f3e-be2f-9ffb584194af)

We should add that and perhaps for orgs too, although you can already filter by org by appending `/org-name` to the URL:

![image](https://github.com/user-attachments/assets/b14d18ca-05aa-4413-820e-cfdc0583900d)

**Comment by 0x4007** [comment]
@gentlementlegen pricing is down now

**Comment by gentlementlegen** [comment]
@0x4007 It seems that the production is also linked to dev https://github.com/ubiquity-os/.ubiquity-os/blob/main/.github/.ubiquity-os.config.dev.yml I shall change it to prod.

**Comment by zugdev** [comment]
can you regen this reward?

**Comment by gentlementlegen** [comment]
@zugdev It seems that your reward got capped when you actually were the assignee that resolved the task, let me fix that and regenerate.

**Comment by 0x4007** [comment]
Actually I think that's correct behavior @gentlementlegen 

It doesn't make sense to have specifications being paid higher than the work that's being done I think. 

The one actually doing the work should get paid the most, excluding the easily game-able incentives, like more communication during the review. 

I think these changes are unnecessary. However you should offer clarity that the reward is capped based on the task reward amount in the breakdown.

**Comment by gentlementlegen** [comment]
Okay then it's a feature not a bug, so rewards basically will be capped at the bounty price. I'll change my PR to display a warning message.
