### ISSUE TITLE
Style adjustments

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#175]
https://404ad59a.devpool-directory-ui.pages.dev/ubiquity-os-marketplace?search=Text-vector-embeddings

![image](https://github.com/user-attachments/assets/65c2aec5-2fd0-4e7c-a714-b1b7442326a7)

- Yeah let's do rounded avatar. I suppose it might look best to match the user avatar to the org avatar on the left in terms of width, height, and placement.  
- check if you can vertical align center on the devpool directory title. Looks a bit low compared to the org icon on the top left 
- disable auto capitalization and spell check in the text search box 

_Originally posted by @0x4007 in https://github.com/ubiquity/work.ubq.fi/pull/170#issuecomment-2509130802_

**Comment by zugdev** [comment]
This is a duplicate of:

#173 
#174 

But jordan is done with it, so your call
