### ISSUE TITLE
Internal Task Listing

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#2]
### Objective

List private tasks for organization collaborators.

1. fork devpool-directory to be devpool-directory-private
2. modify the code of private to get all our private repositories. 
3. check if the user is a member of the organization by querying the user profile details when they log in.
4. if they are a member, then display the private issues from devpool-directory-private

### Original Spec

I want to start a brief discussion/brainstorm around how we should handle this scenario:

Due to a tremendous amount of non-disclosure agreements signed related to card issuance, the card issuance repository has been made private for core team only. 

We have a new task which is of high priority (should be functional in time for fundraising in March) https://github.com/ubiquity/card-issuance/issues/34 

I think that the work.ubq.fi interface is the best for our team to find new tasks to work on, but it can only see public issues, as it loads all of them from the [devpool-directory's issues](https://github.com/ubiquity/devpool-directory/issues). 

https://github.com/ubiquity/work.ubq.fi/blob/69ca27e25a1670cb8c60925de0a670ea61349c36/src/home/fetch-github/fetch-issues-preview.ts#L16

Perhaps the directory can load every issue, including private issues? I'm not sure if its a privacy concern because it exposes the issue title, but without the issue body! Seems like a suboptimal solution but it is the most direct solution.

The issue body in the devpool-directory (mirror) is only a link to the source issue (which requires the user to have permission to view) however from our work.ubq.fi UI, we can use the user's authentication to fetch the issue contents.

**Comment by 0x4007** [comment]
rfc @ubiquity/software-development

**Comment by rndquu** [comment]
> I think that the work.ubq.fi interface is the best for our team to find new tasks to work on, but it can only see public issues, as it loads all of them from the [devpool-directory's issues](https://github.com/ubiquity/devpool-directory/issues).

The core team already sees all of the issues in github's private repos.

This [issue](https://github.com/ubiquity/card-issuance/issues/34) seems to be mission critical so it makes sense to assign it to somebody from the core team hence it's ok to hide it from https://work.ubq.fi/. You've already stated that we need public issues as a sort of triage while high priority features should be implemented by the core team.

Overall I don't see any NDA violations [here](https://github.com/ubiquity/card-issuance/issues/34). If the API provider is worried about exposing its API docs or routes then [here](https://github.com/ubiquity/card-issuance/issues/34) we could:
1. Remove all API provider mentions
2. Remove all URL to docs or routes
3. Make an issue description very general and provide details only on demand (like API docs, routes, etc...)

If we "generalize" issue descriptions at https://github.com/ubiquity/card-issuance we can simply make the whole repo public.

**Comment by 0x4007** [comment]
> The core team already sees all of the issues in github's private repos.

I don't believe that every individual on the team goes through the repositories manually to find new tasks. I do think there is a better chance to make it a habit to have the core team use the work.ubq.fi interface regularly when incentives are implemented and aligned correctly (particularly when compensation is handled entirely by the DevPool system vs base pay/salary.)

> If we "generalize" issue descriptions at https://github.com/ubiquity/card-issuance we can simply make the whole repo public.

I agree but in practice I don't like the idea of tiptoeing around what we can and can not discuss. If its private we don't need to spend extra time or energy worrying about non-disclosure in the form of new tasks, code, documents, or conversation.

**Comment by molecula451** [comment]
it might take a bit but the integration sounds like a bit straightforward for anyone from the core team, btw I am no sure how the idea comes to hide/unhide tasks if we're planning to keep relevancy of the work on work.ubq.fi i still think critical tasks fits best in private over here

**Comment by 0x4007** [comment]
> i still think critical tasks fits best in private over here

You think its best to manually check the private repositories on GitHub for new, high priority tasks?

**Comment by molecula451** [comment]
perhaps a subdomain does it! core.work.ubq.fi

**Comment by 0x4007** [comment]
Okay so you're suggesting an entirely new approach from the UI where the flow is: 
1. Authenticate with GitHub (mandatory to proceed to next step) 
2. Load the issues across all of our private repositories

This makes sense but unfortunately seems work intensive (it sort of makes the existing logic, and the existing [devpool-directory issues](https://github.com/ubiquity/devpool-directory/issues) redundant.)

**Comment by molecula451** [comment]
Crypto Top-Up Card + Ubiquity (Dollar) Staking Shares Enable + Github issues to be tackled in proportional + Super Pull request reviewing 🤑 let it come

**Comment by gitcoindev** [comment]
Or create a private `devpool-directory-private-repositories` / `devpool-directory-restricted` or a similar named GitHub repository which would collect tasks from private repositories and would be accessible only to the core team. 

The internal devpool for private repositories could also be integrated with https://work.ubq.fi/ after login by adding a button 'Core team tasks for private repos'. Visible for core team only, would fetch issues from devpool-directory-private-repositories. But I would see this only as a nice to have feature.

**Comment by 0x4007** [comment]
This approach is interesting because it's basically forking the "backend" which means it should be quick to set up!

`ubiquity-internal-directory`

On the UI we can probably make an extra network request based on if the logged in user is a collaborator on the organization. 

I see how it can scale to other partners from the front end but not sure on the backend.

**Comment by kamaalsultan** [comment]
Is it core-team only issue? @pavlovcik

**Comment by 0x4007** [comment]
It can be done by external contributors but it would be significantly more burdensome to set up. I do not recommend you take on this task. 

You would need to set up all of the infrastructure, which includes 1. a new organization 2. fork the devpool directory for your organization 3. private repositories with mock issues and the correct labels to work with the devpool directory.

**Comment by kamaalsultan** [comment]
> It can be done by external contributors but it would be significantly more burdensome to set up. I do not recommend you take on this task.
> 
> You would need to set up all of the infrastructure, which includes 1. a new organization 2. fork the devpool directory for your organization 3. private repositories with mock issues and the correct labels to work with the devpool directory.

Is it complicated?

**Comment by devpanther** [comment]
@pavlovcik since there is a sign-in with GitHub on work.ubq.fi, I think we can display ard issuance issues if the signed-in user has access to it.

is this up for the taking or has anything changed?

**Comment by 0x4007** [comment]
> @pavlovcik since there is a sign-in with GitHub on work.ubq.fi, I think we can display ard issuance issues if the signed-in user has access to it.
> 
> 
> 
> is this up for the taking or has anything changed?

If it is that simple then let's do it. I assumed we had to make custom accommodations beyond just authenticating one request?

**Comment by 0x4007** [comment]
You can try your approach if that works but I'm skeptical

**Comment by devpanther** [comment]
> You can try your approach if that works but I'm skeptical

It's going to work but more than 2 hours.. the bot is going to get the authenticated user PAT to fetch the private repos (if it does not fetch then they don't have access, I picture a `checkForAccess` type of function so it skips fetching if they don't have access

The only problem is we have to list the private repos somewhere because they aren't sent to one place like the `devpool-directory`

**Comment by rndquu** [comment]
> Or create a private `devpool-directory-private-repositories` / `devpool-directory-restricted` or a similar named GitHub repository which would collect tasks from private repositories and would be accessible only to the core team.
> 
> The internal devpool for private repositories could also be integrated with https://work.ubq.fi/ after login by adding a button 'Core team tasks for private repos'. Visible for core team only, would fetch issues from devpool-directory-private-repositories. But I would see this only as a nice to have feature.

That's a good idea.

I assume https://work.ubq.fi/ works this way:
1. If user is not authorized then use some public PAT to fetch issues from https://github.com/ubiquity/devpool-directory
2. Otherwise use the user's github's PAT to fetch from https://github.com/ubiquity/devpool-directory

We could:
1. Fork https://github.com/ubiquity/devpool-directory into https://github.com/ubiquity/devpool-directory-private and set only private repos there
2. Update https://work.ubq.fi/ to fetch issues from https://github.com/ubiquity/devpool-directory and https://github.com/ubiquity/devpool-directory-private (if repo is available for the authorized user)

**Comment by 0x4007** [comment]
> > Or create a private `devpool-directory-private-repositories` / `devpool-directory-restricted` or a similar named GitHub repository which would collect tasks from private repositories and would be accessible only to the core team.
> > The internal devpool for private repositories could also be integrated with https://work.ubq.fi/ after login by adding a button 'Core team tasks for private repos'. Visible for core team only, would fetch issues from devpool-directory-private-repositories. But I would see this only as a nice to have feature.
> 
> That's a good idea.
> 
> I assume https://work.ubq.fi/ works this way:
> 
> 1. If user is not authorized then use some public PAT to fetch issues from https://github.com/ubiquity/devpool-directory
> 2. Otherwise use the user's github's PAT to fetch from https://github.com/ubiquity/devpool-directory
> 
> We could:
> 
> 1. Fork https://github.com/ubiquity/devpool-directory into https://github.com/ubiquity/devpool-directory-private and set only private repos there
> 2. Update https://work.ubq.fi/ to fetch issues from https://github.com/ubiquity/devpool-directory and https://github.com/ubiquity/devpool-directory-private (if repo is available for the authorized user)

My concern with this idea is that this approach doesn't work for partner organizations. Perhaps its a premature objective but it would have been preferred to find a solution that we can implement once and can add value for everyone. 

> I assume https://work.ubq.fi/ works this way:

GitHub allows for 60 public requests per IP address per minute. The UI is adaptive and makes use of this limitation by making requests only to the essential "preview" information from the client. With increased limits, it will go on and fetch all the issue details etc.

**Comment by 0x4007** [comment]
Updated the spec @devpanther will need to add you to the org so you can handle receiving the private repo data.

**Comment by devpanther** [comment]
> My concern with this idea is that this approach doesn't work for partner organizations. Perhaps its a premature objective but it would have been preferred to find a solution that we can implement once and can add value for everyone.

Maybe we can have a select or something when a user is authorised, we can either list all available private pools and once selected loads it'd the issues or return `You do not have access to this pool` if they don't have access, 

then partners can go ahead and create their own private devpool (if its feasible) and we'd add it to the list of private pool options

**Comment by devpanther** [comment]
I don't know how well this would work

**Comment by 0x4007** [comment]
Just follow the spec and don't worry about accommodating other orgs for now. We will make a new task for that later this year

**Comment by devpanther** [comment]
I forked the repository but i don't think forked repos can be made private @pavlovcik

**Comment by 0x4007** [comment]
You can make a new repo and push the code to make your own copy

**Comment by devpanther** [comment]
> You can make a new repo and push the code to make your own copy

Yea, i thought of that but new codes on the main devpool would have to be manually pushed to the private then as opposed to syncing if it were a fork

**Comment by devpanther** [comment]
Can you help me delete [this](https://github.com/ubiquity/devpool-directory-private-old)

**Comment by devpanther** [comment]
I'd also need the secrets here: https://github.com/ubiquity/devpool-directory-private @pavlovcik, I don't have access to do that. The actions are failing right now because there is no repo-level APP ID and PK

**Comment by 0x4007** [comment]
You don't need Twitter keys for this feature just do a workaround in the code if it's not designed for that

**Comment by devpanther** [comment]
> You don't need Twitter keys for this feature just do a workaround in the code if it's not designed for that

I mean it's not reading the APP ID and APP PRIVATE KEY..

Those are required to run

**Comment by rndquu** [comment]
@devpanther Can you make it work with your own test organization first?

**Comment by 0x4007** [comment]
> > You don't need Twitter keys for this feature just do a workaround in the code if it's not designed for that
> 
> I mean it's not reading the APP ID and APP PRIVATE KEY..
> 
> Those are required to run

All the secrets are organization wide for this reason. Ensure you didn't change the property names. I'm not sure what else to tell you because they work on the other repos. 

Once you have it working with your own org, then it should definitely worked when it's merged in here. 

![image](https://github.com/ubiquity/work.ubq.fi/assets/4975670/0288ff85-d038-4cc0-bd00-9c48668baf35)

**Comment by devpanther** [comment]
> > > You don't need Twitter keys for this feature just do a workaround in the code if it's not designed for that
> > 
> > I mean it's not reading the APP ID and APP PRIVATE KEY..
> > 
> > Those are required to run
> 
> All the secrets are organization wide for this reason. Ensure you didn't change the property names. I'm not sure what else to tell you because they work on the other repos. 
> 
> Once you have it working with your own org, then it should definitely worked when it's merged in here. 

I saw a thread that says private repository don't get access to org keys, I don't know the code should work out of the box if it'd work.. 

working on it on my branch and merging it in at this point won't change the fact that its not reading the secrets

**Comment by molecula451** [comment]
i think it's getting this limitation then the task should be move to a core-full access contributor to avoid these things

**Comment by devpanther** [comment]
> i think it's getting this limitation then the task should be move to a core-full access contributor to avoid these things

I think I'd just work on the rest and the core access contributor will handle the secrets issue once i merge my codes in

**Comment by molecula451** [comment]
> > i think it's getting this limitation then the task should be move to a core-full access contributor to avoid these things
> 
> I think I'd just work on the rest and the core access contributor will handle the secrets issue once i merge my codes in

Yeah i think its a good move

**Comment by 0x4007** [comment]
I already added @devpanther to the team for this project

**Comment by devpanther** [comment]
@pavlovcik is a tag showing `private` on the card and a toggle to show/hide private jobs good?

**Comment by devpanther** [comment]
<img width="825" alt="Screenshot 2024-03-05 at 1 35 31 PM" src="https://github.com/ubiquity/work.ubq.fi/assets/42383942/a252a60b-b5e0-48aa-9421-c54878c56d18">

**Comment by 0x4007** [comment]
> @pavlovcik is a tag showing `private` on the card and a toggle to show/hide private jobs good?

I think just mix and don't highlight it for now. I'll know better when I try it out but I think that there isn't much benefit to highlighting it for now.

**Comment by devpanther** [comment]
> > @pavlovcik is a tag showing `private` on the card and a toggle to show/hide private jobs good?
> 
> I think just mix and don't highlight it for now. I'll know better when I try it out but I think that there isn't much benefit to highlighting it for now.

Okay, I'd just hide it for now

**Comment by 0x4007** [comment]
@devpanther the behavior of [opt.json](https://github.com/ubiquity/devpool-directory-private/blob/development/opt.json) is not clear to me. 

Does this ONLY pay attention to private repos? Otherwise opt.json must redundatly include the values of the public [opt.json](https://github.com/ubiquity/devpool-directory/blob/development/opt.json)

**Comment by 0x4007** [comment]
I spent some time configuring this but unfortunately it doesn't seem to be working.

**Comment by devpanther** [comment]
> @devpanther the behavior of [opt.json](https://github.com/ubiquity/devpool-directory-private/blob/development/opt.json) is not clear to me. 
> 
> Does this ONLY pay attention to private repos? Otherwise opt.json must redundatly include the values of the public [opt.json](https://github.com/ubiquity/devpool-directory/blob/development/opt.json) 

Yea, it only pays attention to private repository.. the link you sent is for the public devpool though, the opt.json there shows every repository on ubiquity except the one on the `out`

**Comment by devpanther** [comment]
@pavlovcik with the new opt.json config, it now shows the public repos.. the way its setup before works..

I removed wildcards like `ubiquity` and added only the ones we want to watch specifically

**Comment by devpanther** [comment]
I would go set it up again, just let me know the repos you want to show on private devpool

**Comment by devpanther** [comment]
<img width="830" alt="Screenshot 2024-03-08 at 9 53 02 AM" src="https://github.com/ubiquity/work.ubq.fi/assets/42383942/4140ac09-4f50-444c-855b-facf285a27bf">

There's an error `fetchAndMergeOptJson` is failing to run and halts the whole script execution when it fails

**Comment by 0x4007** [comment]
Let's do all the private repos

**Comment by devpanther** [comment]
@pavlovcik It should be set now.. i refactored [`fetchAndMergeOptJson`](https://github.com/ubiquity/devpool-directory-private/blob/59d5b5d86ae6a52396d190c710a80c5c698ecd54/helpers/github.ts#L244)

It was overriding the local instead of merging with it

**Comment by devpanther** [comment]
just 3 private repos: https://github.com/ubiquity/devpool-directory-private/blob/development/opt.json

**Comment by 0x4007** [comment]
> > @devpanther the behavior of [opt.json](https://github.com/ubiquity/devpool-directory-private/blob/development/opt.json) is not clear to me. 
> > 
> > Does this ONLY pay attention to private repos? Otherwise opt.json must redundatly include the values of the public [opt.json](https://github.com/ubiquity/devpool-directory/blob/development/opt.json) 
> 
> Yea, it only pays attention to private repository.. the link you sent is for the public devpool though, the opt.json there shows every repository on ubiquity except the one on the `out`

This is obviously not true 

https://github.com/ubiquity/devpool-directory-private/issues/53

**Comment by 0x4007** [comment]
> just 3 private repos: https://github.com/ubiquity/devpool-directory-private/blob/development/opt.json

This should be all of the ubiquity and ubiquibot org. We can selectively opt out later.

**Comment by devpanther** [comment]
> This should be all of the ubiquity and ubiquibot org. We can selectively opt out later.

just like this?

https://github.com/ubiquity/devpool-directory-private/blob/development/opt.json

**Comment by devpanther** [comment]
That'd mean we need to opt out every repo we don't want as opposed to adding the repo we need only

**Comment by devpanther** [comment]
For now, i'm going to opt-out all the public repos

**Comment by devpanther** [comment]
> This is obviously not true

@pavlovcik this setup worked.. i think the previous implementation already pulled in those repo and it cannot delete them so it just closes them

**Comment by devpanther** [comment]
Or can it delete them?

The issues its showing right now are private issues only: https://github.com/ubiquity/devpool-directory-private/issues

This task is closed (for example) because its not part of the privates and it could not delete it: https://github.com/ubiquity/devpool-directory-private/issues/52

**Comment by devpanther** [comment]
@pavlovcik can you confirm this

**Comment by rndquu** [comment]
@devpanther I think you can set the [out array](https://github.com/ubiquity/devpool-directory-private/blob/development/opt.json#L8-L21) to be empty since it doesn't have any effect with the current `in` [setup](https://github.com/ubiquity/devpool-directory-private/blob/development/opt.json#L3-L5)

**Comment by devpanther** [comment]
> @devpanther I think you can set the [out array](https://github.com/ubiquity/devpool-directory-private/blob/development/opt.json#L8-L21) to be empty since it doesn't have any effect with the current `in` [setup](https://github.com/ubiquity/devpool-directory-private/blob/development/opt.json#L3-L5)

Yes

**Comment by devpanther** [comment]
I emptied it

**Comment by devpanther** [comment]
I think https://work.ubq.fi/ shows private now, or is there anything else?

**Comment by rndquu** [comment]
> I think https://work.ubq.fi/ shows private now, or is there anything else?

I can see private issues at https://work.ubq.fi/, works as expected

**Comment by 0x4007** [comment]
<b><h3><a href="https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiIxNTI0MzAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiNjk1NjA0MDcyNzcyNjczMjM5ODIxOTU4NTMxNzI1ODg2NTc4MjkxODU0NDM0Nzg0NTM0MzAzNDc0MTc4NTkwODYzNDYxNDU0NDgwODciLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweGY3NkYxQUNCNjYwMjBmODkzYzk1MzcxZjc0MDU0OUYzMTJERUEzZjEiLCJyZXF1ZXN0ZWRBbW91bnQiOiIxNTI0MzAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHg0NENhMTVEYjEwMWZEMWMxOTQ0NjdEYjZBRjBjNjdDNkJiRjRBQjUxIiwic2lnbmF0dXJlIjoiMHhjNzM2MGQ4NjU2YmM3NjA0Yzg4YWJkYmQzZWFjZmI5MDkxODMwOGM3MDE1Y2M2OGYyNGY0OGJlMzUyMTUzNzkwMGYzOWJiNzFiYjMzMDA4NDQzMmM5MmM2NjAyN2U1OTNmMDc3MWY3YWVlMThhMjA4ZjI1NDdhYWNjOTk3ZmNiOTFiIiwibmV0d29ya0lkIjoxMDB9XQ%3D%3D">[ 1524.3 WXDAI ]</a></h3><h6>@devpanther</h6></b>

**Comment by rndquu** [comment]
Reopening this one because https://github.com/ubiquity/devpool-directory-private can't fetch the latest code from https://github.com/ubiquity/devpool-directory

Possible solutions:
- https://gist.github.com/0xjac/85097472043b697ab57ba1b1c7530274
- https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository#mirroring-a-repository-in-another-location

@devpanther pls fix

**Comment by devpanther** [comment]
Mirroring the repo wasn't part of the original spec, we tried to fork and it failed..

Could've implemented a quick fix without reopening this

**Comment by rndquu** [comment]
> Could've implemented a quick fix without reopening this

It would be really appreciated

**Comment by devpanther** [comment]
@rndquu it is done

**Comment by devpanther** [comment]
They can fetch upstream now on private

**Comment by rndquu** [comment]
> They can fetch upstream now on private

I don't understand, what exactly did you do?

**Comment by devpanther** [comment]
> > They can fetch upstream now on private
> 
> I don't understand, what exactly did you do?

I followed the steps in the link you sent, what else?

It works by adding an upstream so once the main repo is updated, someone needs to pull in the upstream using CMD

**Comment by rndquu** [comment]
> It works by adding an upstream so once the main repo is updated, someone needs to pull in the upstream using CMD

Can't we do it with github UI ?

**Comment by 0x4007** [comment]
> > It works by adding an upstream so once the main repo is updated, someone needs to pull in the upstream using CMD
> 
> 
> 
> Can't we do it with github UI ?

Because this is a private repo we couldn't officially fork the public repo so there isn't a sync button in the GitHub UI

**Comment by rndquu** [comment]
> > > It works by adding an upstream so once the main repo is updated, someone needs to pull in the upstream using CMD
> > 
> > 
> > Can't we do it with github UI ?
> 
> Because this is a private repo we couldn't officially fork the public repo so there isn't a sync button in the GitHub UI

But we could:
1. Setup CI to sync files from `ubiquity/devpool-directory#development` to `ubiquity/devpool-directory-private#upstream`
2. Apply all necessary changes to `ubiquity/devpool-directory-private#development` (like updating `opt.json`)
3. From time to time merge `ubiquity/devpool-directory-private#upstream` to `ubiquity/devpool-directory-private#development` via Github UI
