### ISSUE TITLE
March Adjustments

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#21]
![image](https://github.com/ubiquity/work.ubq.fi/assets/4975670/fa23cbb9-7ca0-4ef7-bec5-e779b6689dbd)

1. No new issue indicators
2. Personal GitHub image doesn't show (it's built for organizations only)

**Comment by Keyrxng** [comment]
What should the default be for showing a new issue indicator? The ``isNew`` was getting wipe after the cache updated every 15 mins, I've hardcoded 3 days but should I move it to env?

**Comment by 0x4007** [comment]
> What should the default be for showing a new issue indicator? The `isNew` was getting wipe after the cache updated every 15 mins, I've hardcoded 3 days but should I move it to env?

Just remove the `isNew` and `isModified` logic entirely because we need to fully reimplement caching for it to work.
