### ISSUE TITLE
GitHub Registration DevRel Tracker

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#30]
### Registration Tracker

- As we ramp up our recruiting efforts, we will provide incentives for developer relations managers to spread the word of the DevPool.
- A major incentive is to reward the DevRel responsible for onboarding any developers that we end up hiring. 
- I anticipate that they can coax and encourage the new candidate to finish one task to make it to getting paid. We may even be able to automate payment generation for the DevRel in the future!

### Scope

We should enable support for trackers i.e. `work.ubq.fi?devrel=diamondnegroni` and then when the developer signs up, we capture the dev and associate them with the devrel for future reference. Refer to https://github.com/ubiquity/work.ubq.fi/issues/30#issuecomment-2008148491 for implementation details. 

# Deadline = EthSeoul Conference 25 March 2024!

**Comment by 0x4007** [comment]
@ubiquity/software-development rfc

**Comment by whilefoo** [comment]
I think this would be fairly easy to implement. Since we are using Cloudflare Pages we can use Pages functions. When a developer comes on the website from a tracker url, we store the ID in the params of the url in local storage and after they sign in with Github a JWT token is stored to local storage which we send to the function along with ID from the param. The function checks if JWT token is valid (because we have the private key of the github app) and stores ID of the signed in user and ID of the person who invited them in a DB or maybe KV so that we don't need to bother with setting up a DB.

**Comment by rndquu** [comment]
This issue basically reimplements [UTM tracking](https://support.google.com/analytics/answer/10917952?hl=en#zippy=%2Cin-this-article).

We can simply:
1. Add Google Analytics script to work.ubq.fi
2. Somehow let "DevRel managers" generate URLs with UTM params like `https://work.ubq.fi?utm_campaign=EthSeoul& utm_content=diamondnegroni `

This way we get:
1. Quick setup
2. Google Analytics dashboard UI
3. Ability to export `EthSeoul` report from Google Analytics dashboard to `.csv` and then to our DB (if we really need it)

**Comment by 0x4007** [comment]
> This issue basically reimplements [UTM tracking](https://support.google.com/analytics/answer/10917952?hl=en#zippy=%2Cin-this-article).
> 
> We can simply:
> 
> 1. Add Google Analytics script to work.ubq.fi
> 2. Somehow let "DevRel managers" generate URLs with UTM params like `https://work.ubq.fi?utm_campaign=EthSeoul& utm_content=diamondnegroni `
> 
> This way we get:
> 
> 1. Quick setup
> 2. Google Analytics dashboard UI
> 3. Ability to export `EthSeoul` report from Google Analytics dashboard to `.csv` and then to our DB (if we really need it)

This is attractive due to it seeming light on workload, but it is not clear to me how we are able to associate the registered developer (signed in with github) with the devrel. 

Sure we will see how many times work.ubq.fi was loaded by referral, but this doesn't provide the GitHub ID (or username) of the referred. 

For context, there are many events over the course of the week. We will have four DevRels competing for rewards all week. We want to compensate high performers well and low performers not much.

**Comment by rndquu** [comment]
> This is attractive due to it seeming light on workload, but it is not clear to me how we are able to associate the registered developer (signed in with github) with the devrel.

Custom events: https://developers.google.com/analytics/devguides/collection/ga4/event-parameters?client_type=gtag#set-up-every-event

How it works:
1. Referral opens `https://work.ubq.fi?utm_campaign=EthSeoul&utm_content=diamondnegroni`
2. `diamondnegroni` is saved in browser's local storage
3. When referral is authenticated via github then send custom event to Google Analytics:
```
gtag('event', 'registration', {
  'referral': 'diamondnegroni',
  'referrer': 'rndquu'
});
```

I think using Google Analytics is less error prone compared to "custom" analytics in supabase

**Comment by gentlementlegen** [comment]
I know Supabase also supports invites by email. I never tested it however, but I think you can add metadata directly to the table linked to the user (goes to `auth.users.user_metadata`).
https://supabase.com/docs/reference/javascript/auth-admin-inviteuserbyemail
It would be useful if we want to keep track within the DB if we want to take actions on this afterwards (reward another user or something).

**Comment by 0x4007** [comment]
> It would be useful if we want to keep track within the DB if we want to take actions on this afterwards (reward another user or something).

Yes but for the sake of our immediate strategic objectives, I think the simple solution (Google Analytics) is optimal. It will be awhile until we really ramp up structured DevRel incentives.

**Comment by whilefoo** [comment]
If we trust them not to cheat then @rndquu idea is the easiest to implement

**Comment by rndquu** [comment]
> If we trust them not to cheat then @rndquu idea is the easiest to implement

As far as I understand "DevRel managers" will get rewards only for contributors who solve at least 1 github issue so it doesn't make many sense in "referral spamming" for referrers

**Comment by 0x4007** [comment]
In the near future (new plugin) would be great to implement DevRel referral incentives. And yes those are only paid out if the referred adds value and makes it to task completion.

**Comment by 0x4007** [comment]
@molecula451 @EresDev are you able to implement this? Seems like most others have deadlines upcoming.

**Comment by molecula451** [comment]
looks like @FernandVEYRIER it's eager to solve it, but if i see it hanging then I step in, if we're gonna make use of the DB then i guess we should add a preview DB schema? or the dev use common sense?

**Comment by 0x4007** [comment]
No database just Google Analytics https://github.com/ubiquity/work.ubq.fi/issues/30#issuecomment-2008148491

**Comment by gentlementlegen** [comment]
> This issue basically reimplements [UTM tracking](https://support.google.com/analytics/answer/10917952?hl=en#zippy=%2Cin-this-article).
> 
> We can simply:
> 
> 1. Add Google Analytics script to work.ubq.fi
> 2. Somehow let "DevRel managers" generate URLs with UTM params like `https://work.ubq.fi?utm_campaign=EthSeoul& utm_content=diamondnegroni `
> 
> This way we get:
> 
> 1. Quick setup
> 2. Google Analytics dashboard UI
> 3. Ability to export `EthSeoul` report from Google Analytics dashboard to `.csv` and then to our DB (if we really need it)

Agree on these steps. We need someone who manages the Analytics account (probably @pavlovcik if there is not one already) then we can add it to the current website.
For point 2 I think it would be cool to be able to get a QR code as it would make the process quite smooth, even more in the context of next week when meeting people who would like to join. Dunno about feasibility.

**Comment by EresDev** [comment]
> @molecula451 @EresDev are you able to implement this? Seems like most others have deadlines upcoming.

The DevRel's referral code would be their GitHub username?

I saw adblockers sometimes blocking Google Analytics. For example, I use uBlock Origin. 

![image](https://github.com/ubiquity/work.ubq.fi/assets/11886219/102cd7e0-dbc9-425e-af31-338f49d4bf2d)

**Comment by molecula451** [comment]
yes the dev also needs the google account

**Comment by 0x4007** [comment]
Bear in mind that this is only urgently needed for the upcoming [EthSeoul week](https://www.ethseoul.org/) https://docs.google.com/spreadsheets/d/1trxM_AmhEutk_GV4j4Hz0lEy-SuDX3nCe_qndLpCbTc/edit#gid=0

We can manually handle payouts etc. @FernandVEYRIER you and I can be "on the ground" and push hotfixes as needed but yes QR seems useful.

> I saw adblockers sometimes blocking Google Analytics. For example, I use uBlock Origin.

People will be on mobile

**Comment by EresDev** [comment]
> People will be on mobile

Great. I can also work on this if you need me to.

**Comment by molecula451** [comment]
> Great. I can also work on this if you need me to.

yes this would be a nice comeback for you

**Comment by 0x4007** [comment]
@EresDev Are you gonna take this over?

**Comment by 0x4007** [comment]
@EresDev i recommend you take a look at the database issue with saving your wallet so we can regenerate your permits!
