### ISSUE TITLE
Lower requested permissions on user registration

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity/work.ubq.fi#41]
When a new user registers to the website and logs in via GitHub, sensitive rights are requested by the app, which is `read / write` on all `public / private` repositories. This seems to be excessive and worrisome for newcomers as they would wonder why we need to write on their private repos. Ideally, we should just request for read permission on public repos. I do not know myself the reason of the request of such elevated rights, so it would be worth investigating. If elevated rights are indeed needed for core members or insiders of the organization, these rights should be requested specifically for these members not for every new user registering.

<img width="259" alt="image" src="https://github.com/ubiquity/work.ubq.fi/assets/9807008/046bfa62-0eb1-4ccd-9465-315ba7c51a05">

**Comment by 0x4007** [comment]
The simple answer, possibly, is to have two logins. 

One intended for users with private repositories that use our bot. For example core team members at Ubiquity. 

The other for public only, intended for new folks.

**Comment by jordan-ae** [comment]
@0x4007  I think an easier solution to implement will be to check the UserType from Github when the person is login in and depending on if it's a newcomer or a core member we can request permissions accordingly.

**Comment by gentlementlegen** [comment]
@jordan-ae Yes that's the idea. You can check for `COLLABORATOR` for team members, anything different would be not a member from the team.

**Comment by jordan-ae** [comment]
@gentlementlegen please can you add  time estimate for this?

**Comment by gentlementlegen** [comment]
@jordan-ae I think two hours should do, with minimal testing. I do not have rights on this repo that's why the bot failed, but you can start the task regardless.

**Comment by jordan-ae** [comment]
Okay jumping on it!

**Comment by gentlementlegen** [comment]
This issue is the story of the snake biting its own tail. To know what scopes to request to a user, we need to know which user it is, so we need the user to log-in. But, we have to request the scopes during the login step. GitHub OAuth doesn't seem to support dynamic scopes, meaning that to change scopes the user needs to logout and login again. Afaik there is no way to also offer optional scopes, where the user could chose.

I think the problem should be solved with UI changes, something like adding a button to request scopes again if the user is a member of the organization. Then, potentially that user could have access to private repos within the org.

**Comment by molecula451** [comment]
@0x4007 👀

**Comment by 0x4007** [comment]
I wonder if it's worth debugging why only admins can generate permits on v1 bot.

**Comment by molecula451** [comment]
> I wonder if it's worth debugging why only admins can generate permits on v1 bot.

it worth it

**Comment by 0x4007** [comment]
Findings can be posted [here](https://github.com/ubiquity/ubiquibot/issues/927).
