### ISSUE TITLE
Issue with No Time estimate and Price find their way to frontend

### ISSUE THREAD

**Issue by jordan-ae** [ubiquity/work.ubq.fi#43]
![Screenshot 2024-04-17 142952](https://github.com/ubiquity/work.ubq.fi/assets/33989423/fca10c1f-1c16-45ee-8894-6b46efb2abf9)

@0x4007 I noticed this issue showed up on the devpool dashboard even though it didnt have a Time estimate and Price label added to it.

**Comment by 0x4007** [comment]
@jordan-ae i just realized something. This should be handled on the "backend" not the front end 

The other repository

**Comment by 0x4007** [comment]
https://github.com/ubiquity/devpool-directory/issues/569

This must be some type of caching issue on your client @jordan-ae

**Comment by jordan-ae** [comment]
> @jordan-ae i just realized something. This should be handled on the "backend" not the front end 


So... should I create this issue there instead. 

> This must be some type of caching issue on your client @jordan-ae

@0x4007 I've cleared my browsers cache and it should be stable now.  But shouldn't we investigate why an issue without labels found its self on the client?

**Comment by 0x4007** [comment]
> > @jordan-ae i just realized something. This should be handled on the "backend" not the front end 
> 
> 
> So... should I create this issue there instead. 
> 
> > This must be some type of caching issue on your client @jordan-ae
> 
> @0x4007 I've cleared my browsers cache and it should be stable now.  But shouldn't we investigate why an issue without labels found its self on the client?

I somewhat agree, but at the same time I've never experienced this and led the development of the UI. I am pretty sure I reloaded and interacted with this UI an order of magnitude more than anybody else and never saw this. 

My hypothesis is that this has to do with the "preview" and "full" task details being temporarily out of sync. I also am guessing that you loaded the page the same time the labels were being updated on the backend

**Comment by 0x4007** [comment]
Please feel free to post your findings here and we can eventually evolve this into a task.

**Comment by rndquu** [comment]
Right now all issues are displayed as expected + there is no clear way to reproduce this issue, closing as "not planned"
