### ISSUE TITLE
Issues Duplicating

### ISSUE THREAD

**Issue by jordan-ae** [ubiquity/work.ubq.fi#44]
![Screenshot 2024-04-17 143312](https://github.com/ubiquity/work.ubq.fi/assets/33989423/b37ac939-dcb1-4fe1-8644-45f1c83ffb31)

@0x4007 When I open the Devpool some issues appear to  be duplicates. This issue has been intermittent for me so far, but it's starting to become abit more frequent. I've tested on Arc browser, Mozilla, Chrome and Safari. And after a couple tries issues duplicate on all browsers.

**Comment by 0x4007** [comment]
Cache related. We will improve later but try clearing your cache and I don't anticipate that it should happen again. I personally haven't had this issue.

**Comment by jordan-ae** [comment]
Okay got it thanks
