### ISSUE TITLE
Proposals/Request for Comment View (`rfc.ubq.fi`)

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#54]
I've opened up a couple of proposals, essentially requests for comment. It could be useful to aggregate them onto a single view for ease-of-access to the DAO. Recent examples:

- https://github.com/ubiquity/.github/issues/111
- https://github.com/ubiquity/.github/issues/110

I imagine that we can find issues without pricing and populate them under the "proposals" view. 

1. Fork this repository, make `rfc.ubq.fi` repository
2. Fork `devpool-directory` repository, make `devpool-rfc` repository 
3. `rfc.ubq.fi` UI should load from `devpool-rfc` "backend"

### A Note on Forks

It seems that we have use cases for similar UI code but for different purposes. Perhaps it makes sense to fork and create new repos (leaderboard.ubq.fi, rfc.ubq.fi.)

In addition, we already have https://github.com/ubiquity/devpool-directory and https://github.com/ubiquity/devpool-directory-private. Ideally we could consolidate everything into a single aggregator repository, and collect even the github issues without pricing. That way we only need to maintain a single repository (instead of potentially three) for our "backend" of issues. 

For now lets just do another fork and then we can worry about consolidating them into a "single backend" in a future project.

**Comment by 0x4007** [comment]
@ubiquity/software-development rfc

**Comment by rndquu** [comment]
Github discussions serve the same purpose.

Regarding a unified UI, we should create a design system first with typography, colors, UI components, etc...([example](https://www.figma.com/design/VkE29ngr7QEp5DB0hfCcs3/Space-DS-(Community)?node-id=127-2&t=gm4p6SxB5RCe8aqC-0))

**Comment by 0x4007** [comment]
> Github discussions serve the same purpose.

We tried using these in the past and it seemed that Issues always were able to handle the business need more effectively than Discussions. In addition, it was an extra step to convert to Issues to start the work. The extra barrier adds friction. That's why we basically no longer use Discussions.

> Regarding a unified UI, we should create a design system first with typography, colors, UI components, etc...([example](https://www.figma.com/design/VkE29ngr7QEp5DB0hfCcs3/Space-DS-(Community)?node-id=127-2&t=gm4p6SxB5RCe8aqC-0))

The closest thing we've got is [dao.ubq.fi/branding](https://dao.ubq.fi/branding) can add more detail at some point though. 

However I was actually referring to the page layout and everything with the list view etc. It seems like it could be useful for all of the applications.

**Comment by 0x4007** [comment]
Alright for now lets just do another fork and then we can worry about consolidating them into a "single backend" in a future project.

**Comment by xno-miner** [comment]
Seems to be working with a test issue. Now https://github.com/xno-miner/rfc.ubq.fi/ and https://github.com/xno-miner/devpool-rfc need to be forked to ubiquity.

**Comment by 0x4007** [comment]
Please show a test deploy link. It doesn't seem possible if your "backend" has no relevant changes https://github.com/ubiquity/devpool-directory/compare/development...xno-miner:devpool-rfc:development

**Comment by xno-miner** [comment]
Oh sorry, I didn't understand the issue fully before, I am currently continuing work.

**Comment by xno-miner** [comment]
I have made the changes that should make the backend work, but I am unable to run the bot locally. Please try it out and check if it works.

**Comment by 0x4007** [comment]
@rndquu would you mind reviewing the "backend" code? As I recall you are the primary author and would likely be the most effective reviewer. 

You can find the "backend" changes here https://github.com/ubiquity/devpool-directory/compare/development...xno-miner:devpool-rfc:development

You can find the proposals directory here https://github.com/xno-miner/devpool-rfc/issues?q=is%3Aissue+

---

@xno-miner the [inverted logic](https://github.com/ubiquity/devpool-directory/compare/development...xno-miner:devpool-rfc:development#diff-7f46e46a8d914909f1e349297b52bd5ecad7f9c4d15c83ac06f75f8981d9ebc5R392) regarding pricing labels:
```typescript
// if issue HAS the "Price" label then skip it
```
Seems to make sense to me so I am inclined to believe that the changes are good 

---

Given that the changes are so small, perhaps it makes sense to just handle them in our [existing backend](https://github.com/ubiquity/devpool-directory/blob/development/helpers/github.ts)? Perhaps you can open a pull to there @xno-miner? I imagine that you can use `if else` conditionals since the logic seemingly is just the opposite.

**Comment by xno-miner** [comment]
I have created the pull request, the changes are described in the pull request description.

https://github.com/ubiquity/devpool-directory/pull/1212

**Comment by Keyrxng** [comment]
I just got pretty confused with these tasks if I'm honest.

The open PR aims to consolidate RFC logic into the current `devpool-directory` and so does this cover item 1 in `Add support for proposals on 'work.ubq.fi': "upgrade backend"`?

This spec implies that the work involved with `rfc.ubq.fi` is a requirement for this task to be completed. Is it expected that this issue won't be complete until the relevant work on the UI is complete too? And if this is true, then is working on `work.ubq.fi` filtering and an additional view as step 2 required in the larger task?

---

Seems like 'double dipping' as it's been called before but it leaves only repo-sync-solution as step 3 of the larger task.

Should we point the open PR towards a dedicated task in https://github.com/ubiquity/devpool-directory-bounties/issues and we can allow item 2 of the larger task to be worked on via this task?

Also https://github.com/ubiquity/devpool-directory-bounties/issues/25 is a duplicate of item 3 of the larger task as well. Some consolidating of the issues would make things a lot clearer

**Comment by 0x4007** [comment]
I think a separate ui is fine (possible fork of this codebase) 

The backend logic must be completed for that new ui to load the right data though. 

Please feel free to do as you see fit with the tasks regarding consolidation.

**Comment by rndquu** [comment]
As far as I understand this issue may be closed as "not planned" because https://work.ubq.fi/ now supports displaying both tasks and proposals.

**Comment by 0x4007** [comment]
@gentlementlegen third reward that didn't render perhaps it's manifest related

**Comment by gentlementlegen** [comment]
@0x4007 Same error as before:
```json
    {
      "message": [
        "Error in event handler",
        "HttpError: This installation has been suspended - https://docs.github.com/rest/reference/apps#create-an-installation-access-token-for-an-app"
      ],
      "level": "error",
      "timestamp": 1728092089294
    }
```

The app is most likely suspended here or on the target repo.

**Comment by 0x4007** [comment]
I'm not sure what to do. We don't want both bots leaving comments

**Comment by gentlementlegen** [comment]
@0x4007 I think we should use `ubiquibot-os` everywhere for now since it is set up.

**Comment by 0x4007** [comment]
Please give me actionable steps or you can fix. I don't understand

**Comment by gentlementlegen** [comment]
The Beta bot won't be able to run if it is not enabled in the other repo and vice versa it seems. We should only use the production bot everywhere probably.

**Comment by 0x4007** [comment]
So we need both bots to have access on marketplace. 

We can have a new switch in the config that defines it's only for beta or production bot to read. 

If the bot doesn't have a valid config then it shouldn't respond to any user actions, like comments and commands.

**Comment by xno-miner** [comment]
Are the payouts fixed yet?
