### ISSUE TITLE
Render Default Image when Avatar Fails to Load

### ISSUE THREAD

**Issue by jordan-ae** [ubiquity/work.ubq.fi#55]
When avatars fail to load, I think it should render a default image or something. Right now when default avatars aren't fetched it doesnt display anything. So the user cant log out because the avatar doubles down as logout button.

![Screenshot 2024-06-03 192445](https://github.com/ubiquity/work.ubq.fi/assets/33989423/f87ef693-a49e-4fa9-8938-42823ea189fb)

**Comment by 0x4007** [comment]
I've never seen that before. Why not just set a minimum width and height for the avatar image and then set a colored background etc. I suppose `#808080` will work for light and dark mode for now. Can be refined later.
