### ISSUE TITLE
New Cache Schema

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#6]
###### Draft

There's several properties we must associate with issues in the context of displaying them correctly. 
1. `origin` - where the issue was loaded from `localStorage | octokit`
   - Any `octokit` origin issue (freshly loaded from the API) should have a visual indicator as being "new"
2. `fullIssueId` - we only load issue previews from `@ubiquity/devpool-directory/issues` and we need to associate the preview issue ID to the "full" issue ID that it points to. 

- I also think that we should immediately display from cache first, and then fetch updates in the background. 
- If an issue is no longer present according to octokit, we need to sync our localStorage (remove the issue) so that it does not display anymore.

**Comment by 0x4007** [comment]
(testing)

**Comment by 0x4007** [comment]
It doesn't remove issues from the UI that are no longer being returned by the GitHub API.

**Comment by kamaalsultan** [comment]
@pavlovcik what about this issue?

**Comment by 0x4007** [comment]
Hey sorry @byteballet @wannacfuture and I were testing the payouts. I already completed this but the payouts aren't working right now.
