### ISSUE TITLE
The user name is not displayed for user who didn't set a name

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity/work.ubq.fi#61]
`name` is not required for a GitHub user, it can be left blank, which results in the UI missing the name of the user.

![image](https://github.com/ubiquity/work.ubq.fi/assets/9807008/be0070b2-f8af-4860-b75c-091cb0b81714)

Maybe it would be better to use the `login` field which is required and cannot be left blank for GitHub users.

See also: https://docs.github.com/en/rest/users/users?apiVersion=2022-11-28#get-a-user

**Comment by 0x4007** [comment]
Should fallback to `login` if name is not found. That seems more proper.
