### ISSUE TITLE
Price filter deleted

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#67]
Signed in and when the lock button renders it deletes the price filter button. @gentlementlegen i think this might be a mistake from when you added this feature. Can't investigate now because on phone. 

![image](https://github.com/ubiquity/work.ubq.fi/assets/4975670/081dc86b-ac49-4eb9-b190-fb88a58be318)

**Comment by gentlementlegen** [comment]
This seems to be more of a CSS issue because on large screens the button is present within the nav bar.
