### ISSUE TITLE
Reimplement Tracking Code

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#74]
Due to the ad blockers, the google analytics reliant version of the devrel tracker is not reliable. We will need to fully redo this feature. Likely will need to be fully custom so this requires storage on the backend. 

- Remove existing google analytics code.
- Set up a storage solution 
- Record referrals. 
- Change query parameter to `ref=`

**Comment by 0x4007** [comment]
> 
> <samp>
> <table>
> <tr><td>Warning!</td> <td>This task was created over 0 days ago. Please confirm that this issue specification is accurate before starting.</td></tr>
> <tr><td>Deadline</td><td>Mon, Jul 29, 9:59 AM UTC</td></tr>
> <tr>
> <td>Registered Wallet</td>
> <td>0x6665c09B7473bd174329B93C13281D1B902bA053</td>
> </tr>
> </table>
> </samp>
>   
> <h6>Tips:</h6>
>     <ul>
>     <li>Use <code>/wallet 0x0000...0000</code> if you want to update your registered payment wallet address.</li>
>     <li>Be sure to open a draft pull request as soon as possible to communicate updates on your progress.</li>
>     <li>Be sure to provide timely updates to us when requested, or you will be automatically unassigned from the task.</li>
>     <ul>
> 

@gentlementlegen There's a lot of differences here

**Comment by gentlementlegen** [comment]
@0x4007 The only difference I see is the warning that should not be here. Is there anything else? I will open a ticket for it.

**Comment by 0x4007** [comment]
Warning and font

**Comment by Keyrxng** [comment]
> Warning and font

Is it the size of the letters? I'm struggling to see a difference sorry

It must be as it's causing `registered wallet` to wrap, if that's the issue I think I know how to solve it

**Comment by gentlementlegen** [comment]
The reason why it takes the full width is because of the long content for the warning, pretty sure the display would be the same for the Bot v1.

**Comment by 0x4007** [comment]
> The reason why it takes the full width is because of the long content for the warning, pretty sure the display would be the same for the Bot v1.

No never seen such a wide font. I see a `<samp>` tag which I've never heard of.

**Comment by rndquu** [comment]
We could detect if adblock is used in js code and (for example) block the whole UI of the https://work.ubq.fi/ with a warning messages like `Pls disable adblock`. This way we can still use the google analytics without implementing a custom storage.

**Comment by 0x4007** [comment]
I think that degrades the UX so I am not onboard with that approach.

**Comment by zugdev** [comment]
> I think that degrades the UX so I am not onboard with that approach.

Also there are ways to bypass js page blockers.

**Comment by zugdev** [comment]
Should I use Supabase for storage?

**Comment by rndquu** [comment]
> Should I use Supabase for storage?

@gentlementlegen @Keyrxng Do we still use supabase for such kind of tasks for saving a map of `user id => reference code`? Or should we stick to cloudflare KV or smth else?

**Comment by rndquu** [comment]
> > I think that degrades the UX so I am not onboard with that approach.
> 
> Also there are ways to bypass js page blockers.

There is a difference between `js blocker + google analytics` which takes 1 hour to implement and a week task for `save ref codes to a DB`.

**Comment by zugdev** [comment]
> > Should I use Supabase for storage?
> 
> @gentlementlegen @Keyrxng Do we still use supabase for such kind of tasks for saving a map of `user id => reference code`? Or should we stick to cloudflare KV or smth else?

Apparently indexedDB is used?
 
> There is a difference between `js blocker + google analytics` which takes 1 hour to implement and a week task for `save ref codes to a DB`.

You have a point :smile:

**Comment by 0x4007** [comment]
Seems like overkill to use Supabase for this. What is the easiest to implement out of the following three? 

1. Supabase - we do still have a UbiquiBot Supabase we use that we can add a table to. 
2. Cloudflare KV - seems conceptually simpler than Supabase.
3. Git commit a JSON file - open sources the data and I think is the most easy to maintain.

**Comment by rndquu** [comment]
> Seems like overkill to use Supabase for this. What is the easiest to implement out of the following three?
> 
> 1. Supabase - we do still have a UbiquiBot Supabase we use that we can add a table to.
> 2. Cloudflare KV - seems conceptually simpler than Supabase.
> 3. Git commit a JSON file - open sources the data and I think is the most easy to maintain.

Since this issue requires a backend and we host all backend-related code in cloudflare functions it seems that it's better to stick to cloudflare KV. As far as I understand we need a single mapping of `referrer_id => referral_id` which are basically github user ids.

**Comment by zugdev** [comment]
I'll refer @koya0 for this one

**Comment by koya0** [comment]
@0x4007 How have you guys currently set up cloudflare KV and auth? I need a reference on how to integrate with your current setup. 

If I need to create a new DB instance I was wondering if an auth header is fine for authentication. I haven't worked with KV before so I'd appreciate any enlightnment regarding this step of the issue.

**Comment by 0x4007** [comment]
I think you just set up your own KV and then we deploy the same config to ours later 

Maybe @whilefoo and @gentlementlegen can add more detail

**Comment by gentlementlegen** [comment]
For the auth, we use Supabase. You would need Docker to run it locally, you can also create a free account and have an online instance.
I realize that the migrations are still located in our old repo:
https://github.com/ubiquity/ubiquibot/tree/development/supabase

For KV, you can either create a free Cloudflare account, or same as Supabase you can run the kernel locally. https://github.com/ubiquity-os/ubiquity-os-kernel
Not sure you need that though.

**Comment by zugdev** [comment]
@0x4007 @rndquu @koya0 `work.ubq.fi` is redirecting to `devpool.directory` on authentication. This happens because `https://devpool.directory/#` is the default URL. **This will be a blocker**. To fix it please check this: https://github.com/ubiquity/work.ubq.fi/pull/107#issuecomment-2396931530. You need to allow redirect to `https://work.ubq.fi/**` and `https://devpool.directory/**` in Supabase.

This is probably the latest supabase setting 

![image](https://github.com/user-attachments/assets/8b93c018-cc9f-4d19-906d-80ed2ad90a98)

**Comment by koya0** [comment]
> @0x4007 @rndquu @koya0 `work.ubq.fi` is redirecting to `devpool.directory` on authentication. This happens because `https://devpool.directory/#` is the default URL. **This will be a blocker**. To fix it please check this: [#107 (comment)](https://github.com/ubiquity/work.ubq.fi/pull/107#issuecomment-2396931530). You need to allow redirect to `https://work.ubq.fi/**` and `https://devpool.directory/**` in Supabase.
> 
> This is probably the latest supabase setting
> 
> ![image](https://private-user-images.githubusercontent.com/155616000/378120969-8b93c018-cc9f-4d19-906d-80ed2ad90a98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNzgxODIsIm5iZiI6MTcyOTM3Nzg4MiwicGF0aCI6Ii8xNTU2MTYwMDAvMzc4MTIwOTY5LThiOTNjMDE4LWNjOWYtNGQxOS05MDZkLTgwZWQyYWQ5MGE5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQyMjQ0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDhiYjg0MjNjZTliNGViYzY2N2VmZmQ1MzgxZWE1NDQyZjAwNDI4ODViNTA4NTNkODlhYjk3MjdhMzlkZTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kswIsHbEq4KKz1dEGGKrVxhcckdlqBDf5rLSUUsarAo)

@zugdev is right, I wasn't able to test the tracker in my Cloudflare Page using the supabase current settings. After the auth, I was being redirected to `devpool.directory`, and the tracker only works if you are redirected to the same url you were before.

Hopefully @zugdev sent me a supabase he set, and allowed the url from my page, after that, I was able to test the tracker and, it's working.

**Comment by 0x4007** [comment]
![image](https://github.com/user-attachments/assets/dff0fa14-9113-4cf2-8d04-aaf81f15865c)

![image](https://github.com/user-attachments/assets/eae30c99-9eba-4ad1-8764-b385ab142eef)

I think it should be the default URL actually. Its cleaner than work.ubq.fi
