### ISSUE TITLE
Fetch all devpool issues

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity/work.ubq.fi#80]
The public and private issue fetch calls do not leverage `octokit.paginate` which is contributing to the current task issue onsite.

**Comment by 0x4007** [comment]
I don't understand the specification. What does pagination solve?

**Comment by Keyrxng** [comment]
> I don't understand the specification. What does pagination solve?

Previously we were restricted to a max of 100 issues without it for both public and private so it is essential we paginate this but I noticed during debugging the current spam bot issue so thought I'd make the issue about that since the quick fix is likely temporary and will be removed
