### ISSUE TITLE
preview deployment auth

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity/work.ubq.fi#82]
The problem is that our preview deployments redirect us to the production portal and so the auth is not valid and we cannot actually test the deployment.

We use `Supabase.auth.signInWithOAuth` to "Login via GitHub". We can optionally pass a `redirectTo` in the options which may resolve this issue. Either generally redirecting back to the same URL it came from or strictly `work.ubq.fi` and a wildcard to match our preview deployment URLs.

I think it would be safer to restrict.

**Comment by 0x4007** [comment]
Time estimate? Also I get around this by capturing the auth token in the query parameter before redirect but this only is feasible on desktop.

**Comment by Keyrxng** [comment]
> Time estimate?

A couple of hours likely

> Also I get around this by capturing the auth token in the query parameter before redirect but this only is feasible on desktop.

I try but I'm never quick enough. Spamming "stop loading" and end up refreshing 😂

**Comment by 0x4007** [comment]
On Mac I use cmd+L and cmd+X to capture the full URL. Then I extract the token and append to my test origin url

**Comment by zugdev** [comment]
Is the preview URL: https://devpool-directory-ui.pages.dev?
