### ISSUE TITLE
Hide unauthorized issues

### ISSUE THREAD

**Issue by rndquu** [ubiquity/work.ubq.fi#84]
There is a small time window for a malicious user to post a new github issue in https://github.com/ubiquity/devpool-directory with a phishing link. Although such [issue](https://github.com/ubiquity/devpool-directory/blob/61045f468246a6fdde9901a400f0f9c1b348272f/.github/workflows/sync-issues.yml#L51) will be deleted eventually users still can be affected.

We could hide issues created by unauthorized users and keep only the ones created by authorized bots:
1. `76412717: https://github.com/ubiquity`
2. `133917611: https://github.com/ubiquibot`
3. `165700353: https://github.com/UbiquityOS`

**Comment by rndquu** [comment]
@Keyrxng FYI

**Comment by 0x4007** [comment]
> @ahmed-1026, this task has been idle for a while. Please provide an update.

@gentlementlegen any idea how this double follow up happened? Could it have been the emoji reaction to the latest comment on the pull?

**Comment by gentlementlegen** [comment]
I am not sure, I have to look at the logs for more details. The emoji might be counted indeed.

**Comment by 0x4007** [comment]
> @ahmed-1026, this task has been idle for a while. Please provide an update.

Disqualification clearly doesn't work as its supposed to anymore.

**Comment by gentlementlegen** [comment]
@0x4007 Didn't you say you reverted some `BOT_ID` variable? It seems that the bot is not ignoring its own comments anymore. @Keyrxng rfc

**Comment by Keyrxng** [comment]
`development` needs three env vars. `BOT_USER_ID` is the `user.id` that you'd get if you hit the `rest.users.fetchByUsername` endpoint with the bot's `app_slug`/username.

![image](https://github.com/user-attachments/assets/dccb01c2-7d8c-43da-868c-0f0f3264df27)

**Comment by 0x4007** [comment]
<img width="831" alt="image" src="https://github.com/user-attachments/assets/0d128d1a-0b64-4b33-b7dc-1e56df9b5d73">

Its [there](https://github.com/ubiquity-os-marketplace/command-start-stop/settings/secrets/actions)

Just updated again to `975031` according to https://github.com/ubiquity-os-marketplace/command-start-stop/pull/35#issuecomment-2336813663

Its unlikely that the value was wrong so I don't believe that is the problem. 

Either way, this solution is flawed. The bot should ignore all bot comments for this as it is not an update from the contributor.

**Comment by Keyrxng** [comment]
1. `BOT_USER_ID` is only required by `command-start-stop` afaik.
2. How can we pull from the issue timeline events which only our bot sent without using it's name or it's user.id? 

```ts
const botUnassigned = unassignedEvents.filter((event) => event.actorId === BOT_USER_ID);
```

3. @gentlementlegen I think you might be mistaken as `user-activity-watcher` did rely on it's own comments although I have removed that logic in https://github.com/ubiquity-os-marketplace/disqualifier/pull/22.

**Comment by gentlementlegen** [comment]
It was just a wild guess, since now it seems that the bot keeps asking for user updates even if nothing is going on, so I thought maybe it's considering its own comments as valid activity.

**Comment by Keyrxng** [comment]
> so I thought maybe it's considering its own comments as valid activity.

Yeah previously we considered the followup as activity in error as we used it as the `lastCheck` marker which I've removed in the linked PR which will resolve that.

**Comment by 0x4007** [comment]
I don't think this is necessary anymore. As soon as any new issue is posted, GitHub Actions will inspect. 
- https://github.com/ubiquity/devpool-directory/pull/1621/files

Will leave it as a normal priority item to be prudent but shouldn't be used much.

**Comment by 0x4007** [comment]
@gentlementlegen disqualify 1. isnt reliable 2. doesnt close pulls when it does work

**Comment by zugdev** [comment]
The web app feeds from the `devpool-issues.json` file: 

```
export async function fetchIssuesFull(): Promise<GitHubIssue[]> {
  const response = await fetch("https://raw.githubusercontent.com/ubiquity/devpool-directory/refs/heads/development/devpool-issues.json");
  const jsonData = await response.json();
  return jsonData;
}
```

In this JSON file the referred issue creator (user) is the original issue poster and not a bot. This means this issue is either about changing how the app fetches issues entirely or the issue is invalid, solely depending on how safe `devpool-issues.json` is. 

A sample issue from running `curl https://raw.githubusercontent.com/ubiquity/devpool-directory/refs/heads/development/devpool-issues.json -o issues.json` where @0x4007 is the issue poster:

```
[
  {
          "url": "https://api.github.com/repos/ubiquity/ubiquity-dollar/issues/964",
          "repository_url": "https://api.github.com/repos/ubiquity/ubiquity-dollar",
          "labels_url": "https://api.github.com/repos/ubiquity/ubiquity-dollar/issues/964/labels{/name}",
          "comments_url": "https://api.github.com/repos/ubiquity/ubiquity-dollar/issues/964/comments",
          "events_url": "https://api.github.com/repos/ubiquity/ubiquity-dollar/issues/964/events",
          "html_url": "https://github.com/ubiquity/ubiquity-dollar/issues/964",
          "id": 2548532846,
          "node_id": "I_kwDOF4fVBs6X54Zu",
          "number": 964,
          "title": "Cloudflare Rate Limiting Too Aggressive",
          "user": {
              "login": "0x4007",
              "id": 4975670,
              "node_id": "MDQ6VXNlcjQ5NzU2NzA=",
              "avatar_url": "https://avatars.githubusercontent.com/u/4975670?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/0x4007",
              "html_url": "https://github.com/0x4007",
              "followers_url": "https://api.github.com/users/0x4007/followers",
              "following_url": "https://api.github.com/users/0x4007/following{/other_user}",
              "gists_url": "https://api.github.com/users/0x4007/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/0x4007/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/0x4007/subscriptions",
              "organizations_url": "https://api.github.com/users/0x4007/orgs",
              "repos_url": "https://api.github.com/users/0x4007/repos",
              "events_url": "https://api.github.com/users/0x4007/events{/privacy}",
              "received_events_url": "https://api.github.com/users/0x4007/received_events",
              "type": "User",
              "site_admin": false
          },
    ...

**Comment by zugdev** [comment]
@rndquu @0x4007 Thinking more about it, it should be invalid I guess. Posting an issue to `devpool-issues` won't imply in appearing at work.ubq.fi unless this issue makes it into `devpool-issues.json`. If that is the case the problem is at `devpool-issues` authentication mechanism and not here.

**Comment by 0x4007** [comment]
This is technically valid for max 15 minutes at a time I think. Basically it's about adding an extra layer of protection/filter in the ui

**Comment by zugdev** [comment]
I understand it's the last safety net, however bot ID won't serve as a filter since the JSON the app consumes contains the original issues and not the ones at `devpool-issues` repo. What I could do is parallel fetch `devpool-issues` repo issues, crosscheck bodys and remove those not authorized. This seems kinda bad in terms of both performance and architecture. Are you sure `devpool-issues.json` JSON file can include a "bad" issue?

**Comment by rndquu** [comment]
@zugdev You're right, current issue seems to be invalid.

https://work.ubq.fi/ gets a list of github issues from the [devpool-issues.json](https://github.com/ubiquity/devpool-directory/blob/c690de0561dd71073353970fdb7d12749f669947/devpool-issues.json) file, not from https://github.com/ubiquity/devpool-directory/issues via github API. The `devpool-issues.json` is a [list](https://github.com/ubiquity/devpool-directory/blob/c690de0561dd71073353970fdb7d12749f669947/helpers/main.ts#L17) of github issues located solely in partners' repos. 

Overall technically a malicious user is still able to create a github issue with a phishing URL in the github's issue description in a partner's repo  which would end up in the "proposals" section of the https://work.ubq.fi/ UI but it won't be shown in the "work" section unless it's funded (i.e. premoderated).
