### ISSUE TITLE
Progressive Web App

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#90]
At this conference, there were several instances where I had bad signal, and I generally like to pitch by showing this interface. 

The problem is that it loads the issues after you load the page so it takes a moment and I'm staring at an empty screen essentially.

Turning this into a progressive Web app should allow us to instantly load the cached issues, even when off-line or disconnected

**Comment by inspikalu** [comment]
Greetings is this task still open. Because it seems like some work has been done on it. Can i go ahead with the task?
@0x4007

**Comment by gentlementlegen** [comment]
@inspikalu As long as there is no one assigned and the tasks is open, you can work on it.

**Comment by akshaydhayal** [comment]
@0x4007 , Can you review the PR?

**Comment by zugdev** [comment]
I believe caching issues in indexedDB and adding an if to not syncTasks if offline would work after #114 will make the issues part of it work.

**Comment by 0x4007** [comment]
Hey @zugdev I noticed the double flicker/render on load after this. Would you mind pushing an adjustment for that? 

I think you might be able to change the render function to compare what it wants to render, with what is already rendered. If its the same thing (as I suspect it will be based on how you implemented it) then skip calling the render function again.

**Comment by zugdev** [comment]
> Hey @zugdev I noticed the double flicker/render on load after this. Would you mind pushing an adjustment for that? 

It happens when your cached issue list is not up to date with the official one. First it renders from cache and in paralel fetches from json. Eventually that promisse returns an issue list, and if cached is different from fetched it will cache and then re-render. I suppose I could bypass the animation for the second run.

**Comment by 0x4007** [comment]
> > Hey @zugdev I noticed the double flicker/render on load after this. Would you mind pushing an adjustment for that?
> 
> It happens when your cached issue list is not up to date with the official one. First it renders from cache and in paralel fetches from json. Eventually that promisse returns an issue list, and if cached is different from fetched it will cache and then re-render. I suppose I could bypass the animation for the second run.

Maybe appending the difference could be ideal, particularly if it is below-the-fold.

**Comment by zugdev** [comment]
Some UUSD payments are working and some are reverting. This one is reverting.

![image](https://github.com/user-attachments/assets/c2b8a6d4-e3d6-4e9a-832e-3b69ae276e5f)

Need to investigate why though. @0x4007

**Comment by gentlementlegen** [comment]
@zugdev When was it generated? We had an issue with permits that was resolved a few days ago, if you show me which one I can re-generate it.

**Comment by zugdev** [comment]
Hey @gentlementlegen here are all four issues I had trouble claiming. One or two are WXDAI but feel free to generate one or multiple UUSD permits.

1. https://github.com/ubiquity/pay.ubq.fi/issues/331  	

2. https://github.com/ubiquity/work.ubq.fi/issues/118			

3. https://github.com/ubiquity/work.ubq.fi/issues/90		

4. https://github.com/ubiquity/pay.ubq.fi/issues/298

**Comment by gentlementlegen** [comment]
@zugdev You should now be able to claim, let me know if the issue persists.

**Comment by zugdev** [comment]
Claimed all, looking good.
