### ISSUE TITLE
Loading Icon

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/work.ubq.fi#93]
A loading icon that matches the style should appear when there are no rows displayed. There tends to be a delay when the page is initially loaded. I envision a white circular spinner.

- It should render in the center of the viewport
- It should be animated
- It should fade out when the rows begin to load. 
- It should timeout after 5-10 seconds and display some type of failure if there is an actual page load failure. 

![work ubq fi_ (1)](https://github.com/user-attachments/assets/3741cbc3-6f0f-4d24-8a8a-d3e67cd9f573)

**Comment by jordan-ae** [comment]
/start 

@0x4007 is the start command down?

**Comment by 0x4007** [comment]
@gentlementlegen there is a problem with permit generation here can you fix?

**Comment by gentlementlegen** [comment]
@0x4007 The error was the following:
```json
{
  "$cloudflare": {
    "truncated": false,
    "event": {
      "request": {
        "url": "https://ubiquity-os-kernel-main.ubq.workers.dev/",
        "method": "POST",
        "path": "/"
      }
    },
    "scriptName": "ubiquity-os-kernel-main",
    "eventType": "fetch",
    "scriptVersion": {
      "id": "429d3939-69e0-471a-bc93-b394bfee29e5"
    },
    "$metadata": {
      "requestId": "8ccb1e079e86dda5",
      "id": "01J98KG2243XZFHGWA0K5Q9R2N",
      "type": "cf-worker",
      "error": "Error in event handler HttpError: This installation has been suspended - https://docs.github.com/rest/reference/apps#create-an-installation-access-token-for-an-app"
    }
  },
  "level": "error",
  "message": "Error in event handler HttpError: This installation has been suspended - https://docs.github.com/rest/reference/apps#create-an-installation-access-token-for-an-app"
}
```

did you change something in the organization settings?

**Comment by 0x4007** [comment]
<img width="839" alt="Screenshot 2024-10-03 at 16 20 37" src="https://github.com/user-attachments/assets/b39cc250-1ce6-4de8-aea2-2f5c8408d30e">

Perhaps it automatically suspends when I don't approve the new permissions? You said its not necessary. Should I reject it?

<img width="933" alt="image" src="https://github.com/user-attachments/assets/d558781b-f965-42b8-a057-dbdc2ec7802f">

**Comment by gentlementlegen** [comment]
@0x4007 Should be running fine once you accept I believe.
